### ISSUE TITLE
Dependency redundence

### ISSUE THREAD

**Issue by zgbkdlm** [AdrienCorenflos/coupled_rejection_sampling#6]
Requirements like `matplotlib`, `tikzplotlib`, `jupyter` are not parts of the package `coupled_rejection_sampling`, hence they shouldn't be listed in `./requirements.txt`. These dependencies are used by the scripts in `./examples` only, I found.

**Comment by AdrienCorenflos** [comment]
Requirements are for reproducibility of the examples indeed.
